title = "Data Model code generator configuration"

[environment]

[logging]
level = "INFO"
log_file = "plaster.log"

[profiles]

[profiles.gdcdictionary]
url = "https://github.com/uc-cdis/mmrf_dictionary.git"
path = "gdcdictionary/schemas"
version = "master"
is_git_tag = false
overwrite = true
type = "remote"
