import sys

from .administered_regimen_line import AdministeredRegimenLine
from .administeredregimenlinedescribescase import AdministeredRegimenLineDescribesCase
from .administeredregimenlinerelatestocase import AdministeredRegimenLineRelatesToCase
from .aggregated_somatic_mutation import AggregatedSomaticMutation
from .aggregatedsomaticmutationdatafromcoremetadatacollection import AggregatedSomaticMutationDataFromCoreMetadataCollection
from .aggregatedsomaticmutationdatafromsomaticaggregationworkflow import AggregatedSomaticMutationDataFromSomaticAggregationWorkflow
from .aggregatedsomaticmutationderivedfromproject import AggregatedSomaticMutationDerivedFromProject
from .aggregatedsomaticmutationrelatestocase import AggregatedSomaticMutationRelatesToCase
from .aligned_reads import AlignedReads
from .aligned_reads_index import AlignedReadsIndex
from .alignedreadsdatafromalignmentcocleaningworkflow import AlignedReadsDataFromAlignmentCocleaningWorkflow
from .alignedreadsdatafromalignmentworkflow import AlignedReadsDataFromAlignmentWorkflow
from .alignedreadsdatafromcoremetadatacollection import AlignedReadsDataFromCoreMetadataCollection
from .alignedreadsindexdatafromcoremetadatacollection import AlignedReadsIndexDataFromCoreMetadataCollection
from .alignedreadsindexderivedfromalignedreads import AlignedReadsIndexDerivedFromAlignedReads
from .alignedreadsindexderivedfromsubmittedalignedreads import AlignedReadsIndexDerivedFromSubmittedAlignedReads
from .alignedreadsindexrelatestocase import AlignedReadsIndexRelatesToCase
from .alignedreadsmatchedtosubmittedalignedreads import AlignedReadsMatchedToSubmittedAlignedReads
from .alignedreadsmatchedtosubmittedunalignedreads import AlignedReadsMatchedToSubmittedUnalignedReads
from .alignedreadsrelatestocase import AlignedReadsRelatesToCase
from .alignment_cocleaning_workflow import AlignmentCocleaningWorkflow
from .alignment_workflow import AlignmentWorkflow
from .alignmentcocleaningworkflowperformedonsubmittedalignedreads import AlignmentCocleaningWorkflowPerformedOnSubmittedAlignedReads
from .alignmentcocleaningworkflowperformedonsubmittedunalignedreads import AlignmentCocleaningWorkflowPerformedOnSubmittedUnalignedReads
from .alignmentcocleaningworkflowrelatestocase import AlignmentCocleaningWorkflowRelatesToCase
from .alignmentworkflowdatafromaliquot import AlignmentWorkflowDataFromAliquot
from .alignmentworkflowperformedonsubmittedalignedreads import AlignmentWorkflowPerformedOnSubmittedAlignedReads
from .alignmentworkflowperformedonsubmittedunalignedreads import AlignmentWorkflowPerformedOnSubmittedUnalignedReads
from .alignmentworkflowrelatestocase import AlignmentWorkflowRelatesToCase
from .aliquot import Aliquot
from .aliquotderivedfromanalyte import AliquotDerivedFromAnalyte
from .aliquotderivedfromsample import AliquotDerivedFromSample
from .aliquotrelatestocase import AliquotRelatesToCase
from .aliquotshippedtocenter import AliquotShippedToCenter
from .analysis_metadata import AnalysisMetadata
from .analysismetadatadatafromcoremetadatacollection import AnalysisMetadataDataFromCoreMetadataCollection
from .analysismetadataderivedfromsubmittedalignedreads import AnalysisMetadataDerivedFromSubmittedAlignedReads
from .analysismetadatarelatestocase import AnalysisMetadataRelatesToCase
from .analyte import Analyte
from .analytederivedfromportion import AnalyteDerivedFromPortion
from .analytederivedfromsample import AnalyteDerivedFromSample
from .analyterelatestocase import AnalyteRelatesToCase
from .annotated_somatic_mutation import AnnotatedSomaticMutation
from .annotatedsomaticmutationdatafromcoremetadatacollection import AnnotatedSomaticMutationDataFromCoreMetadataCollection
from .annotatedsomaticmutationdatafromgenomicprofileharmonizationworkflow import AnnotatedSomaticMutationDataFromGenomicProfileHarmonizationWorkflow
from .annotatedsomaticmutationdatafromsomaticannotationworkflow import AnnotatedSomaticMutationDataFromSomaticAnnotationWorkflow
from .annotatedsomaticmutationrelatestocase import AnnotatedSomaticMutationRelatesToCase
from .archive import Archive
from .archivedatafromcoremetadatacollection import ArchiveDataFromCoreMetadataCollection
from .archivememberofproject import ArchiveMemberOfProject
from .archiverelatestocase import ArchiveRelatesToCase
from .biospecimen_supplement import BiospecimenSupplement
from .biospecimensupplementdatafromcoremetadatacollection import BiospecimenSupplementDataFromCoreMetadataCollection
from .biospecimensupplementderivedfromcase import BiospecimenSupplementDerivedFromCase
from .biospecimensupplementrelatestocase import BiospecimenSupplementRelatesToCase
from .bone_assessment import BoneAssessment
from .boneassessmentdescribescase import BoneAssessmentDescribesCase
from .boneassessmentrelatestocase import BoneAssessmentRelatesToCase
from .case import Case
from .casememberofproject import CaseMemberOfProject
from .center import Center
from .centerdescribesproject import CenterDescribesProject
from .cgs_risk_key_criteria import CgsRiskKeyCriteria
from .cgsriskkeycriteriadescribescase import CgsRiskKeyCriteriaDescribesCase
from .cgsriskkeycriteriarelatestocase import CgsRiskKeyCriteriaRelatesToCase
from .clinical import Clinical
from .clinical_supplement import ClinicalSupplement
from .clinicaldescribescase import ClinicalDescribesCase
from .clinicalrelatestocase import ClinicalRelatesToCase
from .clinicalsupplementdatafromcoremetadatacollection import ClinicalSupplementDataFromCoreMetadataCollection
from .clinicalsupplementderivedfromcase import ClinicalSupplementDerivedFromCase
from .clinicalsupplementrelatestocase import ClinicalSupplementRelatesToCase
from .copy_number_auxiliary_file import CopyNumberAuxiliaryFile
from .copy_number_estimate import CopyNumberEstimate
from .copy_number_liftover_workflow import CopyNumberLiftoverWorkflow
from .copy_number_segment import CopyNumberSegment
from .copy_number_variation_workflow import CopyNumberVariationWorkflow
from .copynumberauxiliaryfiledatafromcoremetadatacollection import CopyNumberAuxiliaryFileDataFromCoreMetadataCollection
from .copynumberauxiliaryfilederivedfromsomaticcopynumberworkflow import CopyNumberAuxiliaryFileDerivedFromSomaticCopyNumberWorkflow
from .copynumberauxiliaryfilerelatestocase import CopyNumberAuxiliaryFileRelatesToCase
from .copynumberestimatedatafromcoremetadatacollection import CopyNumberEstimateDataFromCoreMetadataCollection
from .copynumberestimatederivedfromcopynumbervariationworkflow import CopyNumberEstimateDerivedFromCopyNumberVariationWorkflow
from .copynumberestimatederivedfromgenomicprofileharmonizationworkflow import CopyNumberEstimateDerivedFromGenomicProfileHarmonizationWorkflow
from .copynumberestimatederivedfromsomaticcopynumberworkflow import CopyNumberEstimateDerivedFromSomaticCopyNumberWorkflow
from .copynumberestimaterelatestocase import CopyNumberEstimateRelatesToCase
from .copynumberliftoverworkflowperformedonsubmittedtangentcopynumber import CopyNumberLiftoverWorkflowPerformedOnSubmittedTangentCopyNumber
from .copynumberliftoverworkflowrelatestocase import CopyNumberLiftoverWorkflowRelatesToCase
from .copynumbersegmentdatafromcoremetadatacollection import CopyNumberSegmentDataFromCoreMetadataCollection
from .copynumbersegmentderivedfromcopynumberliftoverworkflow import CopyNumberSegmentDerivedFromCopyNumberLiftoverWorkflow
from .copynumbersegmentderivedfromgenomicprofileharmonizationworkflow import CopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow
from .copynumbersegmentderivedfromsomaticcopynumberworkflow import CopyNumberSegmentDerivedFromSomaticCopyNumberWorkflow
from .copynumbersegmentrelatestocase import CopyNumberSegmentRelatesToCase
from .copynumbervariationworkflowperformedoncopynumbersegment import CopyNumberVariationWorkflowPerformedOnCopyNumberSegment
from .copynumbervariationworkflowrelatestocase import CopyNumberVariationWorkflowRelatesToCase
from .core_metadata_collection import CoreMetadataCollection
from .coremetadatacollectiondatafromproject import CoreMetadataCollectionDataFromProject
from .cytof import Cytof
from .cytofdatafromcoremetadatacollection import CytofDataFromCoreMetadataCollection
from .cytofderivedfromaliquot import CytofDerivedFromAliquot
from .cytofrelatestocase import CytofRelatesToCase
from .data_format import DataFormat
from .data_release import DataRelease
from .data_subtype import DataSubtype
from .data_type import DataType
from .dataformatdescribesfile import DataFormatDescribesFile
from .datareleasedatafromproject import DataReleaseDataFromProject
from .datasubtypememberofdatatype import DataSubtypeMemberOfDataType
from .datatypedescribesfile import DataTypeDescribesFile
from .demographic import Demographic
from .demographicdescribescase import DemographicDescribesCase
from .demographicrelatestocase import DemographicRelatesToCase
from .diagnosis import Diagnosis
from .diagnosisdescribescase import DiagnosisDescribesCase
from .diagnosisrelatestocase import DiagnosisRelatesToCase
from .experiment_metadata import ExperimentMetadata
from .experimental_strategy import ExperimentalStrategy
from .experimentalstrategydescribesfile import ExperimentalStrategyDescribesFile
from .experimentmetadatadatafromcoremetadatacollection import ExperimentMetadataDataFromCoreMetadataCollection
from .experimentmetadataderivedfromreadgroup import ExperimentMetadataDerivedFromReadGroup
from .experimentmetadatarelatestocase import ExperimentMetadataRelatesToCase
from .exposure import Exposure
from .exposuredescribescase import ExposureDescribesCase
from .exposurerelatestocase import ExposureRelatesToCase
from .expression_analysis_workflow import ExpressionAnalysisWorkflow
from .expressionanalysisworkflowperformedongeneexpression import ExpressionAnalysisWorkflowPerformedOnGeneExpression
from .expressionanalysisworkflowrelatestocase import ExpressionAnalysisWorkflowRelatesToCase
from .family_history import FamilyHistory
from .familyhistorydescribescase import FamilyHistoryDescribesCase
from .familyhistoryrelatestocase import FamilyHistoryRelatesToCase
from .file import File
from .filedatafromcase import FileDataFromCase
from .filedatafromcoremetadatacollection import FileDataFromCoreMetadataCollection
from .filememberofarchive import FileMemberOfArchive
from .filerelatestocase import FileRelatesToCase
from .filtered_copy_number_segment import FilteredCopyNumberSegment
from .filteredcopynumbersegmentdatafromcopynumberliftoverworkflow import FilteredCopyNumberSegmentDataFromCopyNumberLiftoverWorkflow
from .filteredcopynumbersegmentdatafromcoremetadatacollection import FilteredCopyNumberSegmentDataFromCoreMetadataCollection
from .filteredcopynumbersegmentrelatestocase import FilteredCopyNumberSegmentRelatesToCase
from .follow_up import FollowUp
from .followupdescribescase import FollowUpDescribesCase
from .followupdescribesdiagnosis import FollowUpDescribesDiagnosis
from .followuprelatestocase import FollowUpRelatesToCase
from .gene_expression import GeneExpression
from .geneexpressiondatafromcoremetadatacollection import GeneExpressionDataFromCoreMetadataCollection
from .geneexpressiondatafromrnaexpressionworkflow import GeneExpressionDataFromRnaExpressionWorkflow
from .geneexpressionrelatestocase import GeneExpressionRelatesToCase
from .genomic_profile_harmonization_workflow import GenomicProfileHarmonizationWorkflow
from .genomicprofileharmonizationworkflowperformedonsubmittedgenomicprofile import GenomicProfileHarmonizationWorkflowPerformedOnSubmittedGenomicProfile
from .genomicprofileharmonizationworkflowrelatestocase import GenomicProfileHarmonizationWorkflowRelatesToCase
from .germline_copy_number_auxiliary_file import GermlineCopyNumberAuxiliaryFile
from .germline_copy_number_estimate import GermlineCopyNumberEstimate
from .germline_copy_number_segment import GermlineCopyNumberSegment
from .germline_copy_number_variation_workflow import GermlineCopyNumberVariationWorkflow
from .germline_copy_number_workflow import GermlineCopyNumberWorkflow
from .germline_mutation_calling_workflow import GermlineMutationCallingWorkflow
from .germline_mutation_index import GermlineMutationIndex
from .germline_structural_variant_calling_workflow import GermlineStructuralVariantCallingWorkflow
from .germline_structural_variation import GermlineStructuralVariation
from .germlinecopynumberauxiliaryfiledatafromcoremetadatacollection import GermlineCopyNumberAuxiliaryFileDataFromCoreMetadataCollection
from .germlinecopynumberauxiliaryfilederivedfromgermlinecopynumberworkflow import GermlineCopyNumberAuxiliaryFileDerivedFromGermlineCopyNumberWorkflow
from .germlinecopynumberauxiliaryfilerelatestocase import GermlineCopyNumberAuxiliaryFileRelatesToCase
from .germlinecopynumberestimatedatafromcoremetadatacollection import GermlineCopyNumberEstimateDataFromCoreMetadataCollection
from .germlinecopynumberestimatederivedfromgenomicprofileharmonizationworkflow import GermlineCopyNumberEstimateDerivedFromGenomicProfileHarmonizationWorkflow
from .germlinecopynumberestimatederivedfromgermlinecopynumbervariationworkflow import GermlineCopyNumberEstimateDerivedFromGermlineCopyNumberVariationWorkflow
from .germlinecopynumberestimatederivedfromgermlinecopynumberworkflow import GermlineCopyNumberEstimateDerivedFromGermlineCopyNumberWorkflow
from .germlinecopynumberestimaterelatestocase import GermlineCopyNumberEstimateRelatesToCase
from .germlinecopynumbersegmentdatafromcoremetadatacollection import GermlineCopyNumberSegmentDataFromCoreMetadataCollection
from .germlinecopynumbersegmentderivedfromgenomicprofileharmonizationworkflow import GermlineCopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow
from .germlinecopynumbersegmentderivedfromgermlinecopynumberworkflow import GermlineCopyNumberSegmentDerivedFromGermlineCopyNumberWorkflow
from .germlinecopynumbersegmentrelatestocase import GermlineCopyNumberSegmentRelatesToCase
from .germlinecopynumbervariationworkflowperformedongermlinecopynumbersegment import GermlineCopyNumberVariationWorkflowPerformedOnGermlineCopyNumberSegment
from .germlinecopynumbervariationworkflowrelatestocase import GermlineCopyNumberVariationWorkflowRelatesToCase
from .germlinecopynumberworkflowperformedonalignedreads import GermlineCopyNumberWorkflowPerformedOnAlignedReads
from .germlinecopynumberworkflowperformedonsubmittedgenotypingarray import GermlineCopyNumberWorkflowPerformedOnSubmittedGenotypingArray
from .germlinecopynumberworkflowrelatestocase import GermlineCopyNumberWorkflowRelatesToCase
from .germlinemutationcallingworkflowperformedonalignedreads import GermlineMutationCallingWorkflowPerformedOnAlignedReads
from .germlinemutationcallingworkflowperformedonsubmittedgenotypingarray import GermlineMutationCallingWorkflowPerformedOnSubmittedGenotypingArray
from .germlinemutationcallingworkflowrelatestocase import GermlineMutationCallingWorkflowRelatesToCase
from .germlinemutationindexdatafromcoremetadatacollection import GermlineMutationIndexDataFromCoreMetadataCollection
from .germlinemutationindexderivedfromgermlinestructuralvariation import GermlineMutationIndexDerivedFromGermlineStructuralVariation
from .germlinemutationindexderivedfromsimplegermlinevariation import GermlineMutationIndexDerivedFromSimpleGermlineVariation
from .germlinemutationindexrelatestocase import GermlineMutationIndexRelatesToCase
from .germlinestructuralvariantcallingworkflowperformedonalignedreads import GermlineStructuralVariantCallingWorkflowPerformedOnAlignedReads
from .germlinestructuralvariantcallingworkflowrelatestocase import GermlineStructuralVariantCallingWorkflowRelatesToCase
from .germlinestructuralvariationdatafromcoremetadatacollection import GermlineStructuralVariationDataFromCoreMetadataCollection
from .germlinestructuralvariationdatafromgenomicprofileharmonizationworkflow import GermlineStructuralVariationDataFromGenomicProfileHarmonizationWorkflow
from .germlinestructuralvariationdatafromgermlinestructuralvariantcallingworkflow import GermlineStructuralVariationDataFromGermlineStructuralVariantCallingWorkflow
from .germlinestructuralvariationrelatestocase import GermlineStructuralVariationRelatesToCase
from .masked_methylation_array import MaskedMethylationArray
from .masked_somatic_mutation import MaskedSomaticMutation
from .maskedmethylationarraydatafromcoremetadatacollection import MaskedMethylationArrayDataFromCoreMetadataCollection
from .maskedmethylationarraydatafrommethylationarrayharmonizationworkflow import MaskedMethylationArrayDataFromMethylationArrayHarmonizationWorkflow
from .maskedmethylationarrayrelatestocase import MaskedMethylationArrayRelatesToCase
from .maskedsomaticmutationdatafromcoremetadatacollection import MaskedSomaticMutationDataFromCoreMetadataCollection
from .maskedsomaticmutationdatafromgenomicprofileharmonizationworkflow import MaskedSomaticMutationDataFromGenomicProfileHarmonizationWorkflow
from .maskedsomaticmutationdatafromsomaticaggregationworkflow import MaskedSomaticMutationDataFromSomaticAggregationWorkflow
from .maskedsomaticmutationderivedfromproject import MaskedSomaticMutationDerivedFromProject
from .maskedsomaticmutationrelatestocase import MaskedSomaticMutationRelatesToCase
from .methylation_array_harmonization_workflow import MethylationArrayHarmonizationWorkflow
from .methylation_beta_value import MethylationBetaValue
from .methylation_liftover_workflow import MethylationLiftoverWorkflow
from .methylationarrayharmonizationworkflowperformedonrawmethylationarray import MethylationArrayHarmonizationWorkflowPerformedOnRawMethylationArray
from .methylationarrayharmonizationworkflowrelatestocase import MethylationArrayHarmonizationWorkflowRelatesToCase
from .methylationbetavaluedatafromcoremetadatacollection import MethylationBetaValueDataFromCoreMetadataCollection
from .methylationbetavaluedatafrommethylationarrayharmonizationworkflow import MethylationBetaValueDataFromMethylationArrayHarmonizationWorkflow
from .methylationbetavaluedatafrommethylationliftoverworkflow import MethylationBetaValueDataFromMethylationLiftoverWorkflow
from .methylationbetavaluerelatestocase import MethylationBetaValueRelatesToCase
from .methylationliftoverworkflowperformedonsubmittedmethylationbetavalue import MethylationLiftoverWorkflowPerformedOnSubmittedMethylationBetaValue
from .methylationliftoverworkflowrelatestocase import MethylationLiftoverWorkflowRelatesToCase
from .mirna_expression import MirnaExpression
from .mirna_expression_workflow import MirnaExpressionWorkflow
from .mirnaexpressiondatafromcoremetadatacollection import MirnaExpressionDataFromCoreMetadataCollection
from .mirnaexpressiondatafrommirnaexpressionworkflow import MirnaExpressionDataFromMirnaExpressionWorkflow
from .mirnaexpressionrelatestocase import MirnaExpressionRelatesToCase
from .mirnaexpressionworkflowperformedonalignedreads import MirnaExpressionWorkflowPerformedOnAlignedReads
from .mirnaexpressionworkflowrelatestocase import MirnaExpressionWorkflowRelatesToCase
from .molecular_test import MolecularTest
from .moleculartestperformedatfollowup import MolecularTestPerformedAtFollowUp
from .moleculartestrelatedtodiagnosis import MolecularTestRelatedToDiagnosis
from .moleculartestrelatedtoslide import MolecularTestRelatedToSlide
from .moleculartestrelatestocase import MolecularTestRelatesToCase
from .other_clinical_attribute import OtherClinicalAttribute
from .otherclinicalattributedescribescase import OtherClinicalAttributeDescribesCase
from .otherclinicalattributedescribesfollowup import OtherClinicalAttributeDescribesFollowUp
from .otherclinicalattributerelatestocase import OtherClinicalAttributeRelatesToCase
from .outcomes import Outcomes
from .outcomesdescribescase import OutcomesDescribesCase
from .outcomesrelatestocase import OutcomesRelatesToCase
from .pathology_detail import PathologyDetail
from .pathology_report import PathologyReport
from .pathologydetaildescribesdiagnosis import PathologyDetailDescribesDiagnosis
from .pathologydetailrelatestocase import PathologyDetailRelatesToCase
from .pathologyreportdatafromcoremetadatacollection import PathologyReportDataFromCoreMetadataCollection
from .pathologyreportderivedfromsample import PathologyReportDerivedFromSample
from .pathologyreportrelatestocase import PathologyReportRelatesToCase
from .platform import Platform
from .platformdescribesfile import PlatformDescribesFile
from .portion import Portion
from .portionderivedfromsample import PortionDerivedFromSample
from .portionrelatestocase import PortionRelatesToCase
from .program import Program
from .project import Project
from .projectmemberofprogram import ProjectMemberOfProgram
from .protein_expression import ProteinExpression
from .proteinexpressiondatafromcoremetadatacollection import ProteinExpressionDataFromCoreMetadataCollection
from .proteinexpressionderivedfromportion import ProteinExpressionDerivedFromPortion
from .proteinexpressionderivedfromsample import ProteinExpressionDerivedFromSample
from .proteinexpressionrelatestocase import ProteinExpressionRelatesToCase
from .raw_methylation_array import RawMethylationArray
from .rawmethylationarraydatafromaliquot import RawMethylationArrayDataFromAliquot
from .rawmethylationarraydatafromcoremetadatacollection import RawMethylationArrayDataFromCoreMetadataCollection
from .rawmethylationarrayrelatestocase import RawMethylationArrayRelatesToCase
from .read_group import ReadGroup
from .read_group_qc import ReadGroupQc
from .readgroupderivedfromaliquot import ReadGroupDerivedFromAliquot
from .readgroupqcdatafromsubmittedalignedreads import ReadGroupQcDataFromSubmittedAlignedReads
from .readgroupqcdatafromsubmittedunalignedreads import ReadGroupQcDataFromSubmittedUnalignedReads
from .readgroupqcgeneratedfromreadgroup import ReadGroupQcGeneratedFromReadGroup
from .readgroupqcrelatestocase import ReadGroupQcRelatesToCase
from .readgrouprelatestocase import ReadGroupRelatesToCase
from .rna_expression_workflow import RnaExpressionWorkflow
from .rnaexpressionworkflowperformedonalignedreads import RnaExpressionWorkflowPerformedOnAlignedReads
from .rnaexpressionworkflowperformedonsubmittedalignedreads import RnaExpressionWorkflowPerformedOnSubmittedAlignedReads
from .rnaexpressionworkflowperformedonsubmittedexpressionarray import RnaExpressionWorkflowPerformedOnSubmittedExpressionArray
from .rnaexpressionworkflowperformedonsubmittedunalignedreads import RnaExpressionWorkflowPerformedOnSubmittedUnalignedReads
from .rnaexpressionworkflowrelatestocase import RnaExpressionWorkflowRelatesToCase
from .run_metadata import RunMetadata
from .runmetadatadatafromcoremetadatacollection import RunMetadataDataFromCoreMetadataCollection
from .runmetadataderivedfromreadgroup import RunMetadataDerivedFromReadGroup
from .runmetadatarelatestocase import RunMetadataRelatesToCase
from .sample import Sample
from .samplederivedfromcase import SampleDerivedFromCase
from .samplerelatedtodiagnosis import SampleRelatedToDiagnosis
from .samplerelatestocase import SampleRelatesToCase
from .secondary_expression_analysis import SecondaryExpressionAnalysis
from .secondaryexpressionanalysisdatafromcoremetadatacollection import SecondaryExpressionAnalysisDataFromCoreMetadataCollection
from .secondaryexpressionanalysisdatafromexpressionanalysisworkflow import SecondaryExpressionAnalysisDataFromExpressionAnalysisWorkflow
from .secondaryexpressionanalysisrelatestocase import SecondaryExpressionAnalysisRelatesToCase
from .signs_symptoms import SignsSymptoms
from .signssymptomsdescribescase import SignsSymptomsDescribesCase
from .signssymptomsrelatestocase import SignsSymptomsRelatesToCase
from .simple_germline_variation import SimpleGermlineVariation
from .simple_somatic_mutation import SimpleSomaticMutation
from .simplegermlinevariationdatafromcoremetadatacollection import SimpleGermlineVariationDataFromCoreMetadataCollection
from .simplegermlinevariationdatafromgermlinemutationcallingworkflow import SimpleGermlineVariationDataFromGermlineMutationCallingWorkflow
from .simplegermlinevariationrelatestocase import SimpleGermlineVariationRelatesToCase
from .simplesomaticmutationdatafromcoremetadatacollection import SimpleSomaticMutationDataFromCoreMetadataCollection
from .simplesomaticmutationdatafromgenomicprofileharmonizationworkflow import SimpleSomaticMutationDataFromGenomicProfileHarmonizationWorkflow
from .simplesomaticmutationdatafromsomaticmutationcallingworkflow import SimpleSomaticMutationDataFromSomaticMutationCallingWorkflow
from .simplesomaticmutationrelatestocase import SimpleSomaticMutationRelatesToCase
from .slide import Slide
from .slide_image import SlideImage
from .slidederivedfromportion import SlideDerivedFromPortion
from .slidederivedfromsample import SlideDerivedFromSample
from .slideimagedatafromcoremetadatacollection import SlideImageDataFromCoreMetadataCollection
from .slideimagedatafromslide import SlideImageDataFromSlide
from .slideimagerelatestocase import SlideImageRelatesToCase
from .sliderelatestocase import SlideRelatesToCase
from .somatic_aggregation_workflow import SomaticAggregationWorkflow
from .somatic_annotation_workflow import SomaticAnnotationWorkflow
from .somatic_copy_number_workflow import SomaticCopyNumberWorkflow
from .somatic_mutation_calling_workflow import SomaticMutationCallingWorkflow
from .somatic_mutation_index import SomaticMutationIndex
from .somaticaggregationworkflowperformedonannotatedsomaticmutation import SomaticAggregationWorkflowPerformedOnAnnotatedSomaticMutation
from .somaticaggregationworkflowperformedonsimplesomaticmutation import SomaticAggregationWorkflowPerformedOnSimpleSomaticMutation
from .somaticaggregationworkflowrelatestocase import SomaticAggregationWorkflowRelatesToCase
from .somaticannotationworkflowperformedonalignedreads import SomaticAnnotationWorkflowPerformedOnAlignedReads
from .somaticannotationworkflowperformedonsimplesomaticmutation import SomaticAnnotationWorkflowPerformedOnSimpleSomaticMutation
from .somaticannotationworkflowrelatestocase import SomaticAnnotationWorkflowRelatesToCase
from .somaticcopynumberworkflowperformedonalignedreads import SomaticCopyNumberWorkflowPerformedOnAlignedReads
from .somaticcopynumberworkflowperformedonsubmittedgenotypingarray import SomaticCopyNumberWorkflowPerformedOnSubmittedGenotypingArray
from .somaticcopynumberworkflowrelatestocase import SomaticCopyNumberWorkflowRelatesToCase
from .somaticmutationcallingworkflowperformedonalignedreads import SomaticMutationCallingWorkflowPerformedOnAlignedReads
from .somaticmutationcallingworkflowrelatestocase import SomaticMutationCallingWorkflowRelatesToCase
from .somaticmutationindexdatafromcoremetadatacollection import SomaticMutationIndexDataFromCoreMetadataCollection
from .somaticmutationindexderivedfromannotatedsomaticmutation import SomaticMutationIndexDerivedFromAnnotatedSomaticMutation
from .somaticmutationindexderivedfromsimplesomaticmutation import SomaticMutationIndexDerivedFromSimpleSomaticMutation
from .somaticmutationindexderivedfromstructuralvariation import SomaticMutationIndexDerivedFromStructuralVariation
from .somaticmutationindexrelatestocase import SomaticMutationIndexRelatesToCase
from .structural_variant_calling_workflow import StructuralVariantCallingWorkflow
from .structural_variation import StructuralVariation
from .structuralvariantcallingworkflowperformedonalignedreads import StructuralVariantCallingWorkflowPerformedOnAlignedReads
from .structuralvariantcallingworkflowrelatestocase import StructuralVariantCallingWorkflowRelatesToCase
from .structuralvariationdatafromcoremetadatacollection import StructuralVariationDataFromCoreMetadataCollection
from .structuralvariationdatafromgenomicprofileharmonizationworkflow import StructuralVariationDataFromGenomicProfileHarmonizationWorkflow
from .structuralvariationdatafromstructuralvariantcallingworkflow import StructuralVariationDataFromStructuralVariantCallingWorkflow
from .structuralvariationrelatestocase import StructuralVariationRelatesToCase
from .submitted_aligned_reads import SubmittedAlignedReads
from .submitted_expression_array import SubmittedExpressionArray
from .submitted_genomic_profile import SubmittedGenomicProfile
from .submitted_genotyping_array import SubmittedGenotypingArray
from .submitted_methylation_beta_value import SubmittedMethylationBetaValue
from .submitted_tangent_copy_number import SubmittedTangentCopyNumber
from .submitted_unaligned_reads import SubmittedUnalignedReads
from .submittedalignedreadsdatafromcoremetadatacollection import SubmittedAlignedReadsDataFromCoreMetadataCollection
from .submittedalignedreadsdatafromreadgroup import SubmittedAlignedReadsDataFromReadGroup
from .submittedalignedreadsrelatestocase import SubmittedAlignedReadsRelatesToCase
from .submittedexpressionarraydatafromcoremetadatacollection import SubmittedExpressionArrayDataFromCoreMetadataCollection
from .submittedexpressionarrayderivedfromaliquot import SubmittedExpressionArrayDerivedFromAliquot
from .submittedexpressionarrayrelatestocase import SubmittedExpressionArrayRelatesToCase
from .submittedgenomicprofiledatafromcoremetadatacollection import SubmittedGenomicProfileDataFromCoreMetadataCollection
from .submittedgenomicprofiledatafromreadgroup import SubmittedGenomicProfileDataFromReadGroup
from .submittedgenomicprofilerelatestocase import SubmittedGenomicProfileRelatesToCase
from .submittedgenotypingarraydatafromcoremetadatacollection import SubmittedGenotypingArrayDataFromCoreMetadataCollection
from .submittedgenotypingarrayderivedfromaliquot import SubmittedGenotypingArrayDerivedFromAliquot
from .submittedgenotypingarrayrelatestocase import SubmittedGenotypingArrayRelatesToCase
from .submittedmethylationbetavaluedatafromcoremetadatacollection import SubmittedMethylationBetaValueDataFromCoreMetadataCollection
from .submittedmethylationbetavaluederivedfromaliquot import SubmittedMethylationBetaValueDerivedFromAliquot
from .submittedmethylationbetavaluerelatestocase import SubmittedMethylationBetaValueRelatesToCase
from .submittedtangentcopynumberdatafromcoremetadatacollection import SubmittedTangentCopyNumberDataFromCoreMetadataCollection
from .submittedtangentcopynumberderivedfromaliquot import SubmittedTangentCopyNumberDerivedFromAliquot
from .submittedtangentcopynumberrelatestocase import SubmittedTangentCopyNumberRelatesToCase
from .submittedunalignedreadsdatafromcoremetadatacollection import SubmittedUnalignedReadsDataFromCoreMetadataCollection
from .submittedunalignedreadsdatafromreadgroup import SubmittedUnalignedReadsDataFromReadGroup
from .submittedunalignedreadsderivedfromaliquot import SubmittedUnalignedReadsDerivedFromAliquot
from .submittedunalignedreadsrelatestocase import SubmittedUnalignedReadsRelatesToCase
from .tag import Tag
from .tagdescribesfile import TagDescribesFile
from .tissue_source_site import TissueSourceSite
from .tissuesourcesitedescribescase import TissueSourceSiteDescribesCase
from .treatment import Treatment
from .treatmentdescribesdiagnosis import TreatmentDescribesDiagnosis
from .treatmentrelatestocase import TreatmentRelatesToCase

from .helpers import base, indexes, related_cases, versioned_nodes, versioning

namespace = base.namespace
Node = base.Node
Edge = base.Edge

__all__ = [
    "AdministeredRegimenLine",
    "AdministeredRegimenLineDescribesCase",
    "AdministeredRegimenLineRelatesToCase",
    "AggregatedSomaticMutation",
    "AggregatedSomaticMutationDataFromCoreMetadataCollection",
    "AggregatedSomaticMutationDataFromSomaticAggregationWorkflow",
    "AggregatedSomaticMutationDerivedFromProject",
    "AggregatedSomaticMutationRelatesToCase",
    "AlignedReads",
    "AlignedReadsIndex",
    "AlignedReadsDataFromAlignmentCocleaningWorkflow",
    "AlignedReadsDataFromAlignmentWorkflow",
    "AlignedReadsDataFromCoreMetadataCollection",
    "AlignedReadsIndexDataFromCoreMetadataCollection",
    "AlignedReadsIndexDerivedFromAlignedReads",
    "AlignedReadsIndexDerivedFromSubmittedAlignedReads",
    "AlignedReadsIndexRelatesToCase",
    "AlignedReadsMatchedToSubmittedAlignedReads",
    "AlignedReadsMatchedToSubmittedUnalignedReads",
    "AlignedReadsRelatesToCase",
    "AlignmentCocleaningWorkflow",
    "AlignmentWorkflow",
    "AlignmentCocleaningWorkflowPerformedOnSubmittedAlignedReads",
    "AlignmentCocleaningWorkflowPerformedOnSubmittedUnalignedReads",
    "AlignmentCocleaningWorkflowRelatesToCase",
    "AlignmentWorkflowDataFromAliquot",
    "AlignmentWorkflowPerformedOnSubmittedAlignedReads",
    "AlignmentWorkflowPerformedOnSubmittedUnalignedReads",
    "AlignmentWorkflowRelatesToCase",
    "Aliquot",
    "AliquotDerivedFromAnalyte",
    "AliquotDerivedFromSample",
    "AliquotRelatesToCase",
    "AliquotShippedToCenter",
    "AnalysisMetadata",
    "AnalysisMetadataDataFromCoreMetadataCollection",
    "AnalysisMetadataDerivedFromSubmittedAlignedReads",
    "AnalysisMetadataRelatesToCase",
    "Analyte",
    "AnalyteDerivedFromPortion",
    "AnalyteDerivedFromSample",
    "AnalyteRelatesToCase",
    "AnnotatedSomaticMutation",
    "AnnotatedSomaticMutationDataFromCoreMetadataCollection",
    "AnnotatedSomaticMutationDataFromGenomicProfileHarmonizationWorkflow",
    "AnnotatedSomaticMutationDataFromSomaticAnnotationWorkflow",
    "AnnotatedSomaticMutationRelatesToCase",
    "Archive",
    "ArchiveDataFromCoreMetadataCollection",
    "ArchiveMemberOfProject",
    "ArchiveRelatesToCase",
    "BiospecimenSupplement",
    "BiospecimenSupplementDataFromCoreMetadataCollection",
    "BiospecimenSupplementDerivedFromCase",
    "BiospecimenSupplementRelatesToCase",
    "BoneAssessment",
    "BoneAssessmentDescribesCase",
    "BoneAssessmentRelatesToCase",
    "Case",
    "CaseMemberOfProject",
    "Center",
    "CenterDescribesProject",
    "CgsRiskKeyCriteria",
    "CgsRiskKeyCriteriaDescribesCase",
    "CgsRiskKeyCriteriaRelatesToCase",
    "Clinical",
    "ClinicalSupplement",
    "ClinicalDescribesCase",
    "ClinicalRelatesToCase",
    "ClinicalSupplementDataFromCoreMetadataCollection",
    "ClinicalSupplementDerivedFromCase",
    "ClinicalSupplementRelatesToCase",
    "CopyNumberAuxiliaryFile",
    "CopyNumberEstimate",
    "CopyNumberLiftoverWorkflow",
    "CopyNumberSegment",
    "CopyNumberVariationWorkflow",
    "CopyNumberAuxiliaryFileDataFromCoreMetadataCollection",
    "CopyNumberAuxiliaryFileDerivedFromSomaticCopyNumberWorkflow",
    "CopyNumberAuxiliaryFileRelatesToCase",
    "CopyNumberEstimateDataFromCoreMetadataCollection",
    "CopyNumberEstimateDerivedFromCopyNumberVariationWorkflow",
    "CopyNumberEstimateDerivedFromGenomicProfileHarmonizationWorkflow",
    "CopyNumberEstimateDerivedFromSomaticCopyNumberWorkflow",
    "CopyNumberEstimateRelatesToCase",
    "CopyNumberLiftoverWorkflowPerformedOnSubmittedTangentCopyNumber",
    "CopyNumberLiftoverWorkflowRelatesToCase",
    "CopyNumberSegmentDataFromCoreMetadataCollection",
    "CopyNumberSegmentDerivedFromCopyNumberLiftoverWorkflow",
    "CopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow",
    "CopyNumberSegmentDerivedFromSomaticCopyNumberWorkflow",
    "CopyNumberSegmentRelatesToCase",
    "CopyNumberVariationWorkflowPerformedOnCopyNumberSegment",
    "CopyNumberVariationWorkflowRelatesToCase",
    "CoreMetadataCollection",
    "CoreMetadataCollectionDataFromProject",
    "Cytof",
    "CytofDataFromCoreMetadataCollection",
    "CytofDerivedFromAliquot",
    "CytofRelatesToCase",
    "DataFormat",
    "DataRelease",
    "DataSubtype",
    "DataType",
    "DataFormatDescribesFile",
    "DataReleaseDataFromProject",
    "DataSubtypeMemberOfDataType",
    "DataTypeDescribesFile",
    "Demographic",
    "DemographicDescribesCase",
    "DemographicRelatesToCase",
    "Diagnosis",
    "DiagnosisDescribesCase",
    "DiagnosisRelatesToCase",
    "ExperimentMetadata",
    "ExperimentalStrategy",
    "ExperimentalStrategyDescribesFile",
    "ExperimentMetadataDataFromCoreMetadataCollection",
    "ExperimentMetadataDerivedFromReadGroup",
    "ExperimentMetadataRelatesToCase",
    "Exposure",
    "ExposureDescribesCase",
    "ExposureRelatesToCase",
    "ExpressionAnalysisWorkflow",
    "ExpressionAnalysisWorkflowPerformedOnGeneExpression",
    "ExpressionAnalysisWorkflowRelatesToCase",
    "FamilyHistory",
    "FamilyHistoryDescribesCase",
    "FamilyHistoryRelatesToCase",
    "File",
    "FileDataFromCase",
    "FileDataFromCoreMetadataCollection",
    "FileMemberOfArchive",
    "FileRelatesToCase",
    "FilteredCopyNumberSegment",
    "FilteredCopyNumberSegmentDataFromCopyNumberLiftoverWorkflow",
    "FilteredCopyNumberSegmentDataFromCoreMetadataCollection",
    "FilteredCopyNumberSegmentRelatesToCase",
    "FollowUp",
    "FollowUpDescribesCase",
    "FollowUpDescribesDiagnosis",
    "FollowUpRelatesToCase",
    "GeneExpression",
    "GeneExpressionDataFromCoreMetadataCollection",
    "GeneExpressionDataFromRnaExpressionWorkflow",
    "GeneExpressionRelatesToCase",
    "GenomicProfileHarmonizationWorkflow",
    "GenomicProfileHarmonizationWorkflowPerformedOnSubmittedGenomicProfile",
    "GenomicProfileHarmonizationWorkflowRelatesToCase",
    "GermlineCopyNumberAuxiliaryFile",
    "GermlineCopyNumberEstimate",
    "GermlineCopyNumberSegment",
    "GermlineCopyNumberVariationWorkflow",
    "GermlineCopyNumberWorkflow",
    "GermlineMutationCallingWorkflow",
    "GermlineMutationIndex",
    "GermlineStructuralVariantCallingWorkflow",
    "GermlineStructuralVariation",
    "GermlineCopyNumberAuxiliaryFileDataFromCoreMetadataCollection",
    "GermlineCopyNumberAuxiliaryFileDerivedFromGermlineCopyNumberWorkflow",
    "GermlineCopyNumberAuxiliaryFileRelatesToCase",
    "GermlineCopyNumberEstimateDataFromCoreMetadataCollection",
    "GermlineCopyNumberEstimateDerivedFromGenomicProfileHarmonizationWorkflow",
    "GermlineCopyNumberEstimateDerivedFromGermlineCopyNumberVariationWorkflow",
    "GermlineCopyNumberEstimateDerivedFromGermlineCopyNumberWorkflow",
    "GermlineCopyNumberEstimateRelatesToCase",
    "GermlineCopyNumberSegmentDataFromCoreMetadataCollection",
    "GermlineCopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow",
    "GermlineCopyNumberSegmentDerivedFromGermlineCopyNumberWorkflow",
    "GermlineCopyNumberSegmentRelatesToCase",
    "GermlineCopyNumberVariationWorkflowPerformedOnGermlineCopyNumberSegment",
    "GermlineCopyNumberVariationWorkflowRelatesToCase",
    "GermlineCopyNumberWorkflowPerformedOnAlignedReads",
    "GermlineCopyNumberWorkflowPerformedOnSubmittedGenotypingArray",
    "GermlineCopyNumberWorkflowRelatesToCase",
    "GermlineMutationCallingWorkflowPerformedOnAlignedReads",
    "GermlineMutationCallingWorkflowPerformedOnSubmittedGenotypingArray",
    "GermlineMutationCallingWorkflowRelatesToCase",
    "GermlineMutationIndexDataFromCoreMetadataCollection",
    "GermlineMutationIndexDerivedFromGermlineStructuralVariation",
    "GermlineMutationIndexDerivedFromSimpleGermlineVariation",
    "GermlineMutationIndexRelatesToCase",
    "GermlineStructuralVariantCallingWorkflowPerformedOnAlignedReads",
    "GermlineStructuralVariantCallingWorkflowRelatesToCase",
    "GermlineStructuralVariationDataFromCoreMetadataCollection",
    "GermlineStructuralVariationDataFromGenomicProfileHarmonizationWorkflow",
    "GermlineStructuralVariationDataFromGermlineStructuralVariantCallingWorkflow",
    "GermlineStructuralVariationRelatesToCase",
    "MaskedMethylationArray",
    "MaskedSomaticMutation",
    "MaskedMethylationArrayDataFromCoreMetadataCollection",
    "MaskedMethylationArrayDataFromMethylationArrayHarmonizationWorkflow",
    "MaskedMethylationArrayRelatesToCase",
    "MaskedSomaticMutationDataFromCoreMetadataCollection",
    "MaskedSomaticMutationDataFromGenomicProfileHarmonizationWorkflow",
    "MaskedSomaticMutationDataFromSomaticAggregationWorkflow",
    "MaskedSomaticMutationDerivedFromProject",
    "MaskedSomaticMutationRelatesToCase",
    "MethylationArrayHarmonizationWorkflow",
    "MethylationBetaValue",
    "MethylationLiftoverWorkflow",
    "MethylationArrayHarmonizationWorkflowPerformedOnRawMethylationArray",
    "MethylationArrayHarmonizationWorkflowRelatesToCase",
    "MethylationBetaValueDataFromCoreMetadataCollection",
    "MethylationBetaValueDataFromMethylationArrayHarmonizationWorkflow",
    "MethylationBetaValueDataFromMethylationLiftoverWorkflow",
    "MethylationBetaValueRelatesToCase",
    "MethylationLiftoverWorkflowPerformedOnSubmittedMethylationBetaValue",
    "MethylationLiftoverWorkflowRelatesToCase",
    "MirnaExpression",
    "MirnaExpressionWorkflow",
    "MirnaExpressionDataFromCoreMetadataCollection",
    "MirnaExpressionDataFromMirnaExpressionWorkflow",
    "MirnaExpressionRelatesToCase",
    "MirnaExpressionWorkflowPerformedOnAlignedReads",
    "MirnaExpressionWorkflowRelatesToCase",
    "MolecularTest",
    "MolecularTestPerformedAtFollowUp",
    "MolecularTestRelatedToDiagnosis",
    "MolecularTestRelatedToSlide",
    "MolecularTestRelatesToCase",
    "OtherClinicalAttribute",
    "OtherClinicalAttributeDescribesCase",
    "OtherClinicalAttributeDescribesFollowUp",
    "OtherClinicalAttributeRelatesToCase",
    "Outcomes",
    "OutcomesDescribesCase",
    "OutcomesRelatesToCase",
    "PathologyDetail",
    "PathologyReport",
    "PathologyDetailDescribesDiagnosis",
    "PathologyDetailRelatesToCase",
    "PathologyReportDataFromCoreMetadataCollection",
    "PathologyReportDerivedFromSample",
    "PathologyReportRelatesToCase",
    "Platform",
    "PlatformDescribesFile",
    "Portion",
    "PortionDerivedFromSample",
    "PortionRelatesToCase",
    "Program",
    "Project",
    "ProjectMemberOfProgram",
    "ProteinExpression",
    "ProteinExpressionDataFromCoreMetadataCollection",
    "ProteinExpressionDerivedFromPortion",
    "ProteinExpressionDerivedFromSample",
    "ProteinExpressionRelatesToCase",
    "RawMethylationArray",
    "RawMethylationArrayDataFromAliquot",
    "RawMethylationArrayDataFromCoreMetadataCollection",
    "RawMethylationArrayRelatesToCase",
    "ReadGroup",
    "ReadGroupQc",
    "ReadGroupDerivedFromAliquot",
    "ReadGroupQcDataFromSubmittedAlignedReads",
    "ReadGroupQcDataFromSubmittedUnalignedReads",
    "ReadGroupQcGeneratedFromReadGroup",
    "ReadGroupQcRelatesToCase",
    "ReadGroupRelatesToCase",
    "RnaExpressionWorkflow",
    "RnaExpressionWorkflowPerformedOnAlignedReads",
    "RnaExpressionWorkflowPerformedOnSubmittedAlignedReads",
    "RnaExpressionWorkflowPerformedOnSubmittedExpressionArray",
    "RnaExpressionWorkflowPerformedOnSubmittedUnalignedReads",
    "RnaExpressionWorkflowRelatesToCase",
    "RunMetadata",
    "RunMetadataDataFromCoreMetadataCollection",
    "RunMetadataDerivedFromReadGroup",
    "RunMetadataRelatesToCase",
    "Sample",
    "SampleDerivedFromCase",
    "SampleRelatedToDiagnosis",
    "SampleRelatesToCase",
    "SecondaryExpressionAnalysis",
    "SecondaryExpressionAnalysisDataFromCoreMetadataCollection",
    "SecondaryExpressionAnalysisDataFromExpressionAnalysisWorkflow",
    "SecondaryExpressionAnalysisRelatesToCase",
    "SignsSymptoms",
    "SignsSymptomsDescribesCase",
    "SignsSymptomsRelatesToCase",
    "SimpleGermlineVariation",
    "SimpleSomaticMutation",
    "SimpleGermlineVariationDataFromCoreMetadataCollection",
    "SimpleGermlineVariationDataFromGermlineMutationCallingWorkflow",
    "SimpleGermlineVariationRelatesToCase",
    "SimpleSomaticMutationDataFromCoreMetadataCollection",
    "SimpleSomaticMutationDataFromGenomicProfileHarmonizationWorkflow",
    "SimpleSomaticMutationDataFromSomaticMutationCallingWorkflow",
    "SimpleSomaticMutationRelatesToCase",
    "Slide",
    "SlideImage",
    "SlideDerivedFromPortion",
    "SlideDerivedFromSample",
    "SlideImageDataFromCoreMetadataCollection",
    "SlideImageDataFromSlide",
    "SlideImageRelatesToCase",
    "SlideRelatesToCase",
    "SomaticAggregationWorkflow",
    "SomaticAnnotationWorkflow",
    "SomaticCopyNumberWorkflow",
    "SomaticMutationCallingWorkflow",
    "SomaticMutationIndex",
    "SomaticAggregationWorkflowPerformedOnAnnotatedSomaticMutation",
    "SomaticAggregationWorkflowPerformedOnSimpleSomaticMutation",
    "SomaticAggregationWorkflowRelatesToCase",
    "SomaticAnnotationWorkflowPerformedOnAlignedReads",
    "SomaticAnnotationWorkflowPerformedOnSimpleSomaticMutation",
    "SomaticAnnotationWorkflowRelatesToCase",
    "SomaticCopyNumberWorkflowPerformedOnAlignedReads",
    "SomaticCopyNumberWorkflowPerformedOnSubmittedGenotypingArray",
    "SomaticCopyNumberWorkflowRelatesToCase",
    "SomaticMutationCallingWorkflowPerformedOnAlignedReads",
    "SomaticMutationCallingWorkflowRelatesToCase",
    "SomaticMutationIndexDataFromCoreMetadataCollection",
    "SomaticMutationIndexDerivedFromAnnotatedSomaticMutation",
    "SomaticMutationIndexDerivedFromSimpleSomaticMutation",
    "SomaticMutationIndexDerivedFromStructuralVariation",
    "SomaticMutationIndexRelatesToCase",
    "StructuralVariantCallingWorkflow",
    "StructuralVariation",
    "StructuralVariantCallingWorkflowPerformedOnAlignedReads",
    "StructuralVariantCallingWorkflowRelatesToCase",
    "StructuralVariationDataFromCoreMetadataCollection",
    "StructuralVariationDataFromGenomicProfileHarmonizationWorkflow",
    "StructuralVariationDataFromStructuralVariantCallingWorkflow",
    "StructuralVariationRelatesToCase",
    "SubmittedAlignedReads",
    "SubmittedExpressionArray",
    "SubmittedGenomicProfile",
    "SubmittedGenotypingArray",
    "SubmittedMethylationBetaValue",
    "SubmittedTangentCopyNumber",
    "SubmittedUnalignedReads",
    "SubmittedAlignedReadsDataFromCoreMetadataCollection",
    "SubmittedAlignedReadsDataFromReadGroup",
    "SubmittedAlignedReadsRelatesToCase",
    "SubmittedExpressionArrayDataFromCoreMetadataCollection",
    "SubmittedExpressionArrayDerivedFromAliquot",
    "SubmittedExpressionArrayRelatesToCase",
    "SubmittedGenomicProfileDataFromCoreMetadataCollection",
    "SubmittedGenomicProfileDataFromReadGroup",
    "SubmittedGenomicProfileRelatesToCase",
    "SubmittedGenotypingArrayDataFromCoreMetadataCollection",
    "SubmittedGenotypingArrayDerivedFromAliquot",
    "SubmittedGenotypingArrayRelatesToCase",
    "SubmittedMethylationBetaValueDataFromCoreMetadataCollection",
    "SubmittedMethylationBetaValueDerivedFromAliquot",
    "SubmittedMethylationBetaValueRelatesToCase",
    "SubmittedTangentCopyNumberDataFromCoreMetadataCollection",
    "SubmittedTangentCopyNumberDerivedFromAliquot",
    "SubmittedTangentCopyNumberRelatesToCase",
    "SubmittedUnalignedReadsDataFromCoreMetadataCollection",
    "SubmittedUnalignedReadsDataFromReadGroup",
    "SubmittedUnalignedReadsDerivedFromAliquot",
    "SubmittedUnalignedReadsRelatesToCase",
    "Tag",
    "TagDescribesFile",
    "TissueSourceSite",
    "TissueSourceSiteDescribesCase",
    "Treatment",
    "TreatmentDescribesDiagnosis",
    "TreatmentRelatesToCase",
]


for __type in __all__:
    cls = sys.modules.get(__name__).__dict__.get(__type)
    cls.post_process()

__all__.append("Node")
__all__.append("Edge")

from sqlalchemy import orm

orm.configure_mappers()