"""This module is for AdministeredRegimenLine Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class AdministeredRegimenLine(base.Node):
    __tablename__: str = "node_administeredregimenline"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Administered Regimen Line', 'namespace': 'https://gdc.cancer.gov', 'category': 'clinical', 'submittable': True, 'downloadable': True, 'description': 'TK', 'required': ['submitter_id', 'type', 'cases'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "administered_regimen_line"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "cases": {
                    "backref": "administered_regimen_line",
                    "type": base.Node.get_subclass("case"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "cases": {
                    "edge_out": "_AdministeredRegimenLineDescribesCase_out",
                    "dst_type": base.Node.get_subclass("case"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def cancer_diagnosis(self, value):
        self._set_property("cancer_diagnosis", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def days_to_regimen_start(self, value):
        self._set_property("days_to_regimen_start", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def days_to_regimen_end(self, value):
        self._set_property("days_to_regimen_end", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def first_line(self, value):
        self._set_property("first_line", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def line(self, value):
        self._set_property("line", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['TK1', 'TK2', 'TK3', 'TK4'])
    def reason_for_discontinuation(self, value):
        self._set_property("reason_for_discontinuation", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def regimen_categories(self, value):
        self._set_property("regimen_categories", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def regimen_duration(self, value):
        self._set_property("regimen_duration", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def regimen_name(self, value):
        self._set_property("regimen_name", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def regimen_short_name(self, value):
        self._set_property("regimen_short_name", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def regimen_type(self, value):
        self._set_property("regimen_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def year_of_regimen_end_date(self, value):
        self._set_property("year_of_regimen_end_date", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def year_of_regimen_start_date(self, value):
        self._set_property("year_of_regimen_start_date", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(AdministeredRegimenLine)
datetime_hooks.cls_inject_updated_datetime_hook(AdministeredRegimenLine)

