"""This module is for AggregatedSomaticMutationDataFromSomaticAggregationWorkflow Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AggregatedSomaticMutationDataFromSomaticAggregationWorkflow(base.Edge):
    __tablename__: str = "edge_3e5c1da2_agsomudafrsoagwo"

    __label__: str = "data_from"
    __dst_class__: str = "SomaticAggregationWorkflow"
    __dst_table__: str = "node_somaticaggregationworkflow"
    __src_class__: str = "AggregatedSomaticMutation"
    __src_table__: str = "node_aggregatedsomaticmutation"

    __dst_src_assoc__: str = "aggregated_somatic_mutations"
    __src_dst_assoc__: str = "somatic_aggregation_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass