"""This module is for AliquotShippedToCenter Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AliquotShippedToCenter(base.Edge):
    __tablename__: str = "edge_aliquotshippedtocenter"

    __label__: str = "shipped_to"
    __dst_class__: str = "Center"
    __dst_table__: str = "node_center"
    __src_class__: str = "Aliquot"
    __src_table__: str = "node_aliquot"

    __dst_src_assoc__: str = "aliquot"
    __src_dst_assoc__: str = "center"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass