"""This module is for Analyte Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class Analyte(base.Node):
    __tablename__: str = "node_analyte"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Analyte', 'namespace': 'https://gdc.cancer.gov', 'category': 'biospecimen', 'submittable': True, 'downloadable': True, 'description': 'A liquid bulk product produced according to specified lab protocols, from a sample or analyte, intended for further analysis.', 'required': ['submitter_id', 'type'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "analyte"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
                "aliquots": {
                    "name": "analytes",
                    "src_type": base.Node.get_subclass("aliquot"),
                },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "aliquots": {
                    "backref": "analytes",
                    "type": base.Node.get_subclass("aliquot"),
                },
                "portions": {
                    "backref": "analytes",
                    "type": base.Node.get_subclass("portion"),
                },
                "samples": {
                    "backref": "analytes",
                    "type": base.Node.get_subclass("sample"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "portions": {
                    "edge_out": "_AnalyteDerivedFromPortion_out",
                    "dst_type": base.Node.get_subclass("portion"),
                },
                "samples": {
                    "edge_out": "_AnalyteDerivedFromSample_out",
                    "dst_type": base.Node.get_subclass("sample"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def a260_a280_ratio(self, value):
        self._set_property("a260_a280_ratio", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def amount(self, value):
        self._set_property("amount", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def analyte_quantity(self, value):
        self._set_property("analyte_quantity", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['DNA', 'EBV Immortalized Normal', 'FFPE DNA', 'FFPE RNA', 'GenomePlex (Rubicon) Amplified DNA', 'Nuclei RNA', 'RNA', 'Repli-G (Qiagen) DNA', 'Repli-G Pooled (Qiagen) DNA', 'Repli-G X (Qiagen) DNA', 'Total RNA', 'cfDNA', 'm6A Enriched RNA'])
    def analyte_type(self, value):
        self._set_property("analyte_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['D', 'E', 'G', 'H', 'R', 'S', 'T', 'W', 'X', 'Y'])
    def analyte_type_id(self, value):
        self._set_property("analyte_type_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def analyte_volume(self, value):
        self._set_property("analyte_volume", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def concentration(self, value):
        self._set_property("concentration", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Allprep FFPE DNA', 'Allprep RNA Extraction', 'Chemical Lysis DNA Extraction', 'Genomplex', 'HighPure miRNA (Allprep DNA) FFPE RNA', 'Pre-extracted DNA received by TSS', 'Repli-G', 'Repli-G X', 'Total RNA', 'aDNA Preparation Type', 'mirVana (Allprep DNA) RNA', 'nRNA - Melanoma Protocol'])
    def experimental_protocol_type(self, value):
        self._set_property("experimental_protocol_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Allowed To Collect', 'Not Reported', 'Unknown', 'Yes'])
    def normal_tumor_genotype_snp_match(self, value):
        self._set_property("normal_tumor_genotype_snp_match", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def ribosomal_rna_28s_16s_ratio(self, value):
        self._set_property("ribosomal_rna_28s_16s_ratio", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def rna_integrity_number(self, value):
        self._set_property("rna_integrity_number", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def spectrophotometer_method(self, value):
        self._set_property("spectrophotometer_method", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def well_number(self, value):
        self._set_property("well_number", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(Analyte)
datetime_hooks.cls_inject_updated_datetime_hook(Analyte)

