"""This module is for Case Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class Case(base.Node):
    __tablename__: str = "node_case"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Case', 'namespace': 'https://gdc.cancer.gov', 'category': 'administrative', 'submittable': True, 'downloadable': True, 'description': 'The collection of all data related to a specific subject in the context of a specific project.', 'required': ['submitter_id', 'type', 'projects'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "case"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
                "administered_regimen_line": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("administered_regimen_line"),
                },
                "biospecimen_supplements": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("biospecimen_supplement"),
                },
                "bone_assessment": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("bone_assessment"),
                },
                "cgs_risk_key_criteria": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("cgs_risk_key_criteria"),
                },
                "clinical_supplements": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("clinical_supplement"),
                },
                "clinicals": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("clinical"),
                },
                "demographics": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("demographic"),
                },
                "diagnoses": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("diagnosis"),
                },
                "exposures": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("exposure"),
                },
                "family_histories": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("family_history"),
                },
                "files": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("file"),
                },
                "follow_ups": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("follow_up"),
                },
                "other_clinical_attributes": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("other_clinical_attribute"),
                },
                "outcomes": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("outcomes"),
                },
                "samples": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("sample"),
                },
                "signs_symptoms": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("signs_symptoms"),
                },
                "tissue_source_sites": {
                    "name": "cases",
                    "src_type": base.Node.get_subclass("tissue_source_site"),
                },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "administered_regimen_line": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("administered_regimen_line"),
                },
                "biospecimen_supplements": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("biospecimen_supplement"),
                },
                "bone_assessment": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("bone_assessment"),
                },
                "cgs_risk_key_criteria": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("cgs_risk_key_criteria"),
                },
                "clinical_supplements": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("clinical_supplement"),
                },
                "clinicals": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("clinical"),
                },
                "demographics": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("demographic"),
                },
                "diagnoses": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("diagnosis"),
                },
                "exposures": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("exposure"),
                },
                "family_histories": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("family_history"),
                },
                "files": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("file"),
                },
                "follow_ups": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("follow_up"),
                },
                "other_clinical_attributes": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("other_clinical_attribute"),
                },
                "outcomes": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("outcomes"),
                },
                "projects": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("project"),
                },
                "samples": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("sample"),
                },
                "signs_symptoms": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("signs_symptoms"),
                },
                "tissue_source_sites": {
                    "backref": "cases",
                    "type": base.Node.get_subclass("tissue_source_site"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "projects": {
                    "edge_out": "_CaseMemberOfProject_out",
                    "dst_type": base.Node.get_subclass("project"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Consent Exemption', 'Consent Waiver', 'Consent by Death', 'Informed Consent'])
    def consent_type(self, value):
        self._set_property("consent_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def days_to_consent(self, value):
        self._set_property("days_to_consent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def days_to_lost_to_followup(self, value):
        self._set_property("days_to_lost_to_followup", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Acinar Cell Neoplasms', 'Adenomas and Adenocarcinomas', 'Adnexal and Skin Appendage Neoplasms', 'Basal Cell Neoplasms', 'Blood Vessel Tumors', 'Chronic Myeloproliferative Disorders', 'Complex Epithelial Neoplasms', 'Complex Mixed and Stromal Neoplasms', 'Cystic, Mucinous and Serous Neoplasms', 'Ductal and Lobular Neoplasms', 'Epithelial Neoplasms, NOS', 'Fibroepithelial Neoplasms', 'Fibromatous Neoplasms', 'Germ Cell Neoplasms', 'Giant Cell Tumors', 'Gliomas', 'Granular Cell Tumors and Alveolar Soft Part Sarcomas', 'Hodgkin Lymphoma', 'Immunoproliferative Diseases', 'Leukemias, NOS', 'Lipomatous Neoplasms', 'Lymphatic Vessel Tumors', 'Lymphoid Leukemias', 'Malignant Lymphomas, NOS or Diffuse', 'Mast Cell Tumors', 'Mature B-Cell Lymphomas', 'Mature T- and NK-Cell Lymphomas', 'Meningiomas', 'Mesonephromas', 'Mesothelial Neoplasms', 'Miscellaneous Bone Tumors', 'Miscellaneous Tumors', 'Mucoepidermoid Neoplasms', 'Myelodysplastic Syndromes', 'Myeloid Leukemias', 'Myomatous Neoplasms', 'Myxomatous Neoplasms', 'Neoplasms of Histiocytes and Accessory Lymphoid Cells', 'Neoplasms, NOS', 'Nerve Sheath Tumors', 'Neuroepitheliomatous Neoplasms', 'Nevi and Melanomas', 'Not Applicable', 'Not Reported', 'Odontogenic Tumors', 'Osseous and Chondromatous Neoplasms', 'Other Hematologic Disorders', 'Other Leukemias', 'Paragangliomas and Glomus Tumors', 'Plasma Cell Tumors', 'Precursor Cell Lymphoblastic Lymphoma', 'Soft Tissue Tumors and Sarcomas, NOS', 'Specialized Gonadal Neoplasms', 'Squamous Cell Neoplasms', 'Synovial-like Neoplasms', 'Thymic Epithelial Neoplasms', 'Transitional Cell Papillomas and Carcinomas', 'Trophoblastic neoplasms', 'Unknown'])
    def disease_type(self, value):
        self._set_property("disease_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Diagnosis', 'First Patient Visit', 'First Treatment', 'Initial Genomic Sequencing', 'Recurrence', 'Sample Procurement', 'Study Enrollment'])
    def index_date(self, value):
        self._set_property("index_date", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Unknown', 'Yes'])
    def lost_to_followup(self, value):
        self._set_property("lost_to_followup", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Accessory sinuses', 'Adrenal gland', 'Anus and anal canal', 'Base of tongue', 'Bladder', 'Bones, joints and articular cartilage of limbs', 'Bones, joints and articular cartilage of other and unspecified sites', 'Brain', 'Breast', 'Bronchus and lung', 'Cervix uteri', 'Colon', 'Connective, subcutaneous and other soft tissues', 'Corpus uteri', 'Esophagus', 'Eye and adnexa', 'Floor of mouth', 'Gallbladder', 'Gum', 'Heart, mediastinum, and pleura', 'Hematopoietic and reticuloendothelial systems', 'Hypopharynx', 'Kidney', 'Larynx', 'Lip', 'Liver and intrahepatic bile ducts', 'Lymph nodes', 'Meninges', 'Nasal cavity and middle ear', 'Nasopharynx', 'Not Applicable', 'Not Reported', 'Oropharynx', 'Other and ill-defined digestive organs', 'Other and ill-defined sites', 'Other and ill-defined sites in lip, oral cavity and pharynx', 'Other and ill-defined sites within respiratory system and intrathoracic organs', 'Other and unspecified female genital organs', 'Other and unspecified major salivary glands', 'Other and unspecified male genital organs', 'Other and unspecified parts of biliary tract', 'Other and unspecified parts of mouth', 'Other and unspecified parts of tongue', 'Other and unspecified urinary organs', 'Other endocrine glands and related structures', 'Ovary', 'Palate', 'Pancreas', 'Parotid gland', 'Penis', 'Peripheral nerves and autonomic nervous system', 'Placenta', 'Prostate gland', 'Pyriform sinus', 'Rectosigmoid junction', 'Rectum', 'Renal pelvis', 'Retroperitoneum and peritoneum', 'Skin', 'Small intestine', 'Spinal cord, cranial nerves, and other parts of central nervous system', 'Stomach', 'Testis', 'Thymus', 'Thyroid gland', 'Tonsil', 'Trachea', 'Unknown', 'Ureter', 'Uterus, NOS', 'Vagina', 'Vulva'])
    def primary_site(self, value):
        self._set_property("primary_site", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(Case)
datetime_hooks.cls_inject_updated_datetime_hook(Case)

