"""This module is for CgsRiskKeyCriteria Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class CgsRiskKeyCriteria(base.Node):
    __tablename__: str = "node_cgsriskkeycriteria"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'CGS Risk Key Criteria', 'namespace': 'https://gdc.cancer.gov', 'category': 'clinical', 'submittable': True, 'downloadable': True, 'description': 'Baseline patient-level Clinical Genomic Scoring (CGS) risk classification and key criteria for multiple myeloma.', 'required': ['submitter_id', 'type', 'cgs_risk_category', 'cases'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "cgs_risk_key_criteria"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "cases": {
                    "backref": "cgs_risk_key_criteria",
                    "type": base.Node.get_subclass("case"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "cases": {
                    "edge_out": "_CgsRiskKeyCriteriaDescribesCase_out",
                    "dst_type": base.Node.get_subclass("case"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['High', 'NA', 'Standard'])
    def cgs_risk_category(self, value):
        self._set_property("cgs_risk_category", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def criteria_1(self, value):
        self._set_property("criteria_1", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def criteria_2(self, value):
        self._set_property("criteria_2", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def criteria_3(self, value):
        self._set_property("criteria_3", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def criteria_4(self, value):
        self._set_property("criteria_4", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_del17p13(self, value):
        self._set_property("has_del17p13", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_tp53_mutation(self, value):
        self._set_property("has_tp53_mutation", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_t414(self, value):
        self._set_property("has_t414", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_t1416(self, value):
        self._set_property("has_t1416", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_t1420(self, value):
        self._set_property("has_t1420", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_1q(self, value):
        self._set_property("has_1q", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_mono_del1p32(self, value):
        self._set_property("has_mono_del1p32", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_bi_del1p32(self, value):
        self._set_property("has_bi_del1p32", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_del1p32(self, value):
        self._set_property("has_del1p32", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_high_b2m(self, value):
        self._set_property("has_high_b2m", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FALSE', 'NA', 'TRUE'])
    def has_normal_creatinine(self, value):
        self._set_property("has_normal_creatinine", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(CgsRiskKeyCriteria)
datetime_hooks.cls_inject_updated_datetime_hook(CgsRiskKeyCriteria)

