"""This module is for CopyNumberSegmentDerivedFromCopyNumberLiftoverWorkflow Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class CopyNumberSegmentDerivedFromCopyNumberLiftoverWorkflow(base.Edge):
    __tablename__: str = "edge_9f05d8e5_conusedefrconuliwo"

    __label__: str = "derived_from"
    __dst_class__: str = "CopyNumberLiftoverWorkflow"
    __dst_table__: str = "node_copynumberliftoverworkflow"
    __src_class__: str = "CopyNumberSegment"
    __src_table__: str = "node_copynumbersegment"

    __dst_src_assoc__: str = "copy_number_segments"
    __src_dst_assoc__: str = "copy_number_liftover_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass