"""This module is for FollowUpDescribesDiagnosis Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class FollowUpDescribesDiagnosis(base.Edge):
    __tablename__: str = "edge_followupdescribesdiagnosis"

    __label__: str = "describes"
    __dst_class__: str = "Diagnosis"
    __dst_table__: str = "node_diagnosis"
    __src_class__: str = "FollowUp"
    __src_table__: str = "node_followup"

    __dst_src_assoc__: str = "follow_ups"
    __src_dst_assoc__: str = "diagnoses"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass