"""This module is for GermlineStructuralVariationDataFromGermlineStructuralVariantCallingWorkflow Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class GermlineStructuralVariationDataFromGermlineStructuralVariantCallingWorkflow(base.Edge):
    __tablename__: str = "edge_8a2ddf3b_gestvadafrgestvacawo"

    __label__: str = "data_from"
    __dst_class__: str = "GermlineStructuralVariantCallingWorkflow"
    __dst_table__: str = "node_germlinestructuralvariantcallingworkflow"
    __src_class__: str = "GermlineStructuralVariation"
    __src_table__: str = "node_germlinestructuralvariation"

    __dst_src_assoc__: str = "germline_structural_variations"
    __src_dst_assoc__: str = "germline_structural_variant_calling_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass