"""This module is for GermlineMutationIndexDerivedFromSimpleGermlineVariation Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class GermlineMutationIndexDerivedFromSimpleGermlineVariation(base.Edge):
    __tablename__: str = "edge_46b53623_gemuindefrsigeva"

    __label__: str = "derived_from"
    __dst_class__: str = "SimpleGermlineVariation"
    __dst_table__: str = "node_simplegermlinevariation"
    __src_class__: str = "GermlineMutationIndex"
    __src_table__: str = "node_germlinemutationindex"

    __dst_src_assoc__: str = "germline_mutation_indexes"
    __src_dst_assoc__: str = "simple_germline_variations"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass