"""This module is for PathologyDetail Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class PathologyDetail(base.Node):
    __tablename__: str = "node_pathologydetail"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Pathology Detail', 'namespace': 'https://gdc.cancer.gov', 'category': 'clinical', 'submittable': True, 'downloadable': True, 'description': 'Information derived from a pathologic review of a specific sample or slide that was not known to be submitted to the GDC.', 'required': ['submitter_id', 'type', 'diagnoses'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "pathology_detail"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "diagnoses": {
                    "backref": "pathology_details",
                    "type": base.Node.get_subclass("diagnosis"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "diagnoses": {
                    "edge_out": "_PathologyDetailDescribesDiagnosis_out",
                    "dst_type": base.Node.get_subclass("diagnosis"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Adenomyosis', 'Asbestos bodies', 'Atrophic endometrium', 'Atypical hyperplasia/Endometrial intraepithelial neoplasia (EIN)', 'Autoimmune atrophic chronic gastritis', 'Benign endocervical polyp', 'Bilateral ovaries with endometriotic cyst and surface adhesions', 'Bone marrow concordant histology', 'Bone marrow discordant histology', 'Carcinoma in situ', 'Cirrhosis', 'Clostridioides difficile (c. diff)', 'Colonization; bacterial', 'Colonization; fungal', 'Cyst(s)', 'Diffuse and early nodular diabetic glomerulosclerosis', 'Dysplasia; high grade', 'Dysplasia; low grade', 'Endometrial polyp', 'Endometriosis', 'Endometroid carcinoma with local mucinous differentiation', 'Endosalpingiosis', 'Epithelial dysplasia', 'Epithelial hyperplasia', 'Extravascular Matrix Loops', 'Gallbladder adenomyomatosis', 'Glomerular disease', 'Hyperkeratosis', 'Inflammation', 'Intestinal metaplasia', 'Keratinizing dysplasia; mild', 'Keratinizing dysplasia; moderate', 'Keratinizing dysplasia; severe (carcinoma in situ)', 'Leiomyoma', 'Leiomyomata w/ degenerative changes', 'Nonkeratinizing dysplasia; mild', 'Nonkeratinizing dysplasia; moderate', 'Nonkeratinizing dysplasia; severe (carcinoma in situ)', 'Other', 'Other Complex Extravascular Matrix Patterns', 'PD-L1 CPS (223C LDT) - 20%', 'Percent follicular component <= 10%', 'Percent follicular component > 10%', 'Platinum-resistant', 'Pleural plaque', 'Poorly Differentiated', 'Pulmonary interstitial fibrosis', 'Sialadenitis', 'Sinonasal papilloma', 'Squamous metaplasia', 'Squamous papilloma; solitary', 'Squamous papillomatosis', 'Tubular (papillary) adenoma(s)', 'Tumor has rough spikey edges', 'Tumor-associated lymphoid proliferation', 'Well Differentiated'])
    def additional_pathology_findings(self, value):
        self._set_property("additional_pathology_findings", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def anaplasia_present(self, value):
        self._set_property("anaplasia_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Absent', 'Diffuse', 'Equivocal', 'Focal', 'Not Reported', 'Present', 'Sclerosis', 'Unknown'])
    def anaplasia_present_type(self, value):
        self._set_property("anaplasia_present_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def bone_marrow_malignant_cells(self, value):
        self._set_property("bone_marrow_malignant_cells", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def breslow_thickness(self, value):
        self._set_property("breslow_thickness", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def circumferential_resection_margin(self, value):
        self._set_property("circumferential_resection_margin", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def columnar_mucosa_present(self, value):
        self._set_property("columnar_mucosa_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def consistent_pathology_review(self, value):
        self._set_property("consistent_pathology_review", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def d_im_flowcyt_pct_pc_in_bm_high(self, value):
        self._set_property("d_im_flowcyt_pct_pc_in_bm_high", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def d_im_flowcyt_pct_pc_in_bm_low(self, value):
        self._set_property("d_im_flowcyt_pct_pc_in_bm_low", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def d_im_flowcyt_pct_pc_in_pb_low(self, value):
        self._set_property("d_im_flowcyt_pct_pc_in_pb_low", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def d_im_morphology_percent_pc_in_bm(self, value):
        self._set_property("d_im_morphology_percent_pc_in_bm", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def d_im_morphology_percent_pc_in_pb(self, value):
        self._set_property("d_im_morphology_percent_pc_in_pb", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def days_to_pathology_detail(self, value):
        self._set_property("days_to_pathology_detail", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['High Grade', 'Indefinite', 'Low Grade', 'Mild', 'Moderate', 'No Dysplasia', 'Not Reported', 'Severe', 'Unknown'])
    def dysplasia_degree(self, value):
        self._set_property("dysplasia_degree", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Epithelial', 'Esophageal Columnar Dysplasia', 'Esophageal Mucosa Columnar Dysplasia', 'Keratinizing', 'Nonkeratinizing', 'Not Reported', 'Other', 'Unknown'])
    def dysplasia_type(self, value):
        self._set_property("dysplasia_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def epithelioid_cell_percent(self, value):
        self._set_property("epithelioid_cell_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['0%', '1-30%', '31-60%', '61-90%', '>90%', 'Not Reported', 'Unknown'])
    def epithelioid_cell_percent_range(self, value):
        self._set_property("epithelioid_cell_percent_range", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Extensive', 'Focal', 'Not Reported', 'Unknown'])
    def extracapsular_extension(self, value):
        self._set_property("extracapsular_extension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def extracapsular_extension_present(self, value):
        self._set_property("extracapsular_extension_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Gross Extension', 'Microscopic Extension', 'No Extranodal Extension', 'Not Reported', 'Unknown'])
    def extranodal_extension(self, value):
        self._set_property("extranodal_extension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['<=5mm', '>5mm', 'Not Reported', 'Unknown'])
    def extraocular_nodule_size(self, value):
        self._set_property("extraocular_nodule_size", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def extrascleral_extension(self, value):
        self._set_property("extrascleral_extension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def extrascleral_extension_present(self, value):
        self._set_property("extrascleral_extension_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Minimal (T3)', 'Moderate/Advanced (T4a)', 'None', 'Not Reported', 'Unknown', 'Very Advanced (T4b)'])
    def extrathyroid_extension(self, value):
        self._set_property("extrathyroid_extension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def greatest_tumor_dimension(self, value):
        self._set_property("greatest_tumor_dimension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def gross_tumor_weight(self, value):
        self._set_property("gross_tumor_weight", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Anaplastic', 'Not Reported', 'Poorly differentiated', 'Unknown'])
    def histologic_progression_type(self, value):
        self._set_property("histologic_progression_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def intratubular_germ_cell_neoplasia_present(self, value):
        self._set_property("intratubular_germ_cell_neoplasia_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def keatsnfkb_index(self, value):
        self._set_property("keatsnfkb_index", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def keatsprolif_index(self, value):
        self._set_property("keatsprolif_index", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Macroscopic (2cm or less)', 'Macroscopic (greater than 2cm)', 'Microscopic', 'Not Reported', 'Unknown'])
    def largest_extrapelvic_peritoneal_focus(self, value):
        self._set_property("largest_extrapelvic_peritoneal_focus", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Functional (Limited) Neck Dissection', 'Modified Radical Neck Dissection', 'Radical Neck Dissection'])
    def lymph_node_dissection_method(self, value):
        self._set_property("lymph_node_dissection_method", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Neck, Left', 'Neck, NOS', 'Neck, Right', 'Not Reported', 'Retroperitoneal', 'Unknown'])
    def lymph_node_dissection_site(self, value):
        self._set_property("lymph_node_dissection_site", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Aortic', 'Axillary', 'Cervical', 'Cervical, Central', 'Cervical, Lateral', 'Cervical, NOS', 'Epitrochlear', 'Femoral', 'Hilar', 'Iliac, NOS', 'Iliac-common', 'Iliac-external', 'Inguinal', 'Intra-Abdominal, NOS', 'Mediastinal', 'Mesenteric', 'None', 'Not Reported', 'Occipital', 'Paraaortic', 'Parotid', 'Pelvis, NOS', 'Popliteal', 'Retroperitoneal', 'Splenic', 'Submandibular', 'Supraclavicular', 'Unknown'])
    def lymph_node_involved_site(self, value):
        self._set_property("lymph_node_involved_site", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Indeterminant', 'Negative', 'Not Reported', 'Positive', 'Unknown'])
    def lymph_node_involvement(self, value):
        self._set_property("lymph_node_involvement", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def lymph_nodes_positive(self, value):
        self._set_property("lymph_nodes_positive", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def lymph_nodes_removed(self, value):
        self._set_property("lymph_nodes_removed", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def lymph_nodes_tested(self, value):
        self._set_property("lymph_nodes_tested", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def lymphatic_invasion_present(self, value):
        self._set_property("lymphatic_invasion_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Indeterminant', 'Involved', 'Not Reported', 'Uninvolved', 'Unknown'])
    def margin_status(self, value):
        self._set_property("margin_status", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Echographic', 'Not Reported', 'Pathologic', 'Radiologic', 'Unknown'])
    def measurement_type(self, value):
        self._set_property("measurement_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Centimeters', 'Millimeters', 'Not Reported', 'Unknown'])
    def measurement_unit(self, value):
        self._set_property("measurement_unit", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def metaplasia_present(self, value):
        self._set_property("metaplasia_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def micrometastasis_present(self, value):
        self._set_property("micrometastasis_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Cohesive', 'Cribiform', 'Micropapillary', 'Non-cohesive', 'Not Reported', 'Papillary Renal Cell', 'Papillary, NOS', 'Solid', 'Tubular', 'Unknown'])
    def morphologic_architectural_pattern(self, value):
        self._set_property("morphologic_architectural_pattern", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def necrosis_percent(self, value):
        self._set_property("necrosis_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def necrosis_present(self, value):
        self._set_property("necrosis_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Absent', 'Indeterminate', 'Not Reported', 'Present', 'Unknown'])
    def non_nodal_regional_disease(self, value):
        self._set_property("non_nodal_regional_disease", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def non_nodal_tumor_deposits(self, value):
        self._set_property("non_nodal_tumor_deposits", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def number_proliferating_cells(self, value):
        self._set_property("number_proliferating_cells", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def percent_tumor_invasion(self, value):
        self._set_property("percent_tumor_invasion", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def percent_tumor_nuclei(self, value):
        self._set_property("percent_tumor_nuclei", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def perineural_invasion_present(self, value):
        self._set_property("perineural_invasion_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['0', '1-3', '4 or More', 'Not Reported', 'Unknown'])
    def peripancreatic_lymph_nodes_positive(self, value):
        self._set_property("peripancreatic_lymph_nodes_positive", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def peripancreatic_lymph_nodes_tested(self, value):
        self._set_property("peripancreatic_lymph_nodes_tested", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def pi_pbl_call(self, value):
        self._set_property("pi_pbl_call", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def pi_pbl_index(self, value):
        self._set_property("pi_pbl_index", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Not Reported', 'Type 1', 'Type 2', 'Unknown'])
    def prcc_type(self, value):
        self._set_property("prcc_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def prostatic_chips_positive_count(self, value):
        self._set_property("prostatic_chips_positive_count", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def prostatic_chips_total_count(self, value):
        self._set_property("prostatic_chips_total_count", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def prostatic_involvement_percent(self, value):
        self._set_property("prostatic_involvement_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Not Reported', 'R0', 'R1', 'R2', 'RX', 'Unknown'])
    def residual_tumor(self, value):
        self._set_property("residual_tumor", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['1-10 mm', '11-20 mm', '>20 mm', 'No macroscopic disease', 'Not Reported', 'Unknown'])
    def residual_tumor_measurement(self, value):
        self._set_property("residual_tumor_measurement", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def rhabdoid_percent(self, value):
        self._set_property("rhabdoid_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def rhabdoid_present(self, value):
        self._set_property("rhabdoid_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def sarcomatoid_percent(self, value):
        self._set_property("sarcomatoid_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def sarcomatoid_present(self, value):
        self._set_property("sarcomatoid_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def size_extraocular_nodule(self, value):
        self._set_property("size_extraocular_nodule", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def spindle_cell_percent(self, value):
        self._set_property("spindle_cell_percent", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['0%', '1-30%', '31-60%', '61-90%', '>90%', 'Not Reported', 'Unknown'])
    def spindle_cell_percent_range(self, value):
        self._set_property("spindle_cell_percent_range", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Adjuvant Therapy', 'Adolescence', 'Adulthood', 'After Chemotherapy', 'After Study Enrollment', 'Childhood', 'End of Consolidation Therapy', 'End of Treatment Course', 'End of Treatment Course 1', 'End of Treatment Course 2', 'First Complete Response', 'First Treatment', 'Follow-up', 'Initial Diagnosis', 'Last Contact', 'Not Reported', 'Other', 'Post Adjuvant Therapy', 'Post Hormone Therapy', 'Post Initial Treatment', 'Post Secondary Therapy', 'Postoperative', 'Preoperative', 'Prior to Adjuvant Therapy', 'Prior to Chemotherapy', 'Prior to Diagnosis', 'Prior to Procurement', 'Prior to Study Enrollment', 'Prior to Study Registration', 'Prior to Treatment', 'Progression', 'Recurrence', 'Recurrence/Progression', 'Sample Procurement', 'Unknown', 'Within 2 Months After Completion of First-Course Treatment', 'Within 3 Months of Surgery'])
    def timepoint_category(self, value):
        self._set_property("timepoint_category", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Absent', 'Not Reported', 'Present', 'Unknown'])
    def transglottic_extension(self, value):
        self._set_property("transglottic_extension", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_basal_diameter(self, value):
        self._set_property("tumor_basal_diameter", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_burden(self, value):
        self._set_property("tumor_burden", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Deep', 'Not Reported', 'Superficial', 'Unknown'])
    def tumor_depth_descriptor(self, value):
        self._set_property("tumor_depth_descriptor", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_depth_measurement(self, value):
        self._set_property("tumor_depth_measurement", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Few', 'Many', 'Moderate', 'Not Reported', 'Unknown'])
    def tumor_infiltrating_lymphocytes(self, value):
        self._set_property("tumor_infiltrating_lymphocytes", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Few', 'Many', 'Moderate', 'Not Reported', 'Unknown'])
    def tumor_infiltrating_macrophages(self, value):
        self._set_property("tumor_infiltrating_macrophages", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_largest_dimension_diameter(self, value):
        self._set_property("tumor_largest_dimension_diameter", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_length_measurement(self, value):
        self._set_property("tumor_length_measurement", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(list )
    def tumor_level_prostate(self, value):
        self._set_property("tumor_level_prostate", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Diffuse', 'Dome', 'Mushroom', 'Not Reported', 'Unknown'])
    def tumor_shape(self, value):
        self._set_property("tumor_shape", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_thickness(self, value):
        self._set_property("tumor_thickness", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(float, int )
    def tumor_width_measurement(self, value):
        self._set_property("tumor_width_measurement", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def uams70_call(self, value):
        self._set_property("uams70_call", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def uams70_index(self, value):
        self._set_property("uams70_index", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['No', 'Not Reported', 'Unknown', 'Yes'])
    def vascular_invasion_present(self, value):
        self._set_property("vascular_invasion_present", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Extramural', 'Intramural', 'Macro', 'Micro', 'No Vascular Invasion', 'Not Reported', 'Unknown'])
    def vascular_invasion_type(self, value):
        self._set_property("vascular_invasion_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Central zone', 'Not Reported', 'Overlapping/multiple zones', 'Peripheral zone', 'Transition zone', 'Unknown zone'])
    def zone_of_origin_prostate(self, value):
        self._set_property("zone_of_origin_prostate", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(PathologyDetail)
datetime_hooks.cls_inject_updated_datetime_hook(PathologyDetail)

