"""This module is for Project Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class Project(base.Node):
    __tablename__: str = "node_project"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['code']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'awg_review': False, 'in_review': False, 'is_legacy': False, 'state': 'open', 'release_requested': False, 'released': False, 'releasable': False, 'request_submission': False, 'submission_enabled': True}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Project', 'namespace': 'https://gdc.cancer.gov', 'category': 'administrative', 'submittable': True, 'downloadable': True, 'description': 'Any specifically defined piece of work that is undertaken or attempted to meet a single requirement. (NCIt C47885)', 'required': ['code', 'type', 'name', 'state', 'programs', 'dbgap_accession_number'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "project"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
                "aggregated_somatic_mutations": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("aggregated_somatic_mutation"),
                },
                "archives": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("archive"),
                },
                "cases": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("case"),
                },
                "centers": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("center"),
                },
                "core_metadata_collections": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("core_metadata_collection"),
                },
                "data_releases": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("data_release"),
                },
                "masked_somatic_mutations": {
                    "name": "projects",
                    "src_type": base.Node.get_subclass("masked_somatic_mutation"),
                },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "aggregated_somatic_mutations": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("aggregated_somatic_mutation"),
                },
                "archives": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("archive"),
                },
                "cases": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("case"),
                },
                "centers": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("center"),
                },
                "core_metadata_collections": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("core_metadata_collection"),
                },
                "data_releases": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("data_release"),
                },
                "masked_somatic_mutations": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("masked_somatic_mutation"),
                },
                "programs": {
                    "backref": "projects",
                    "type": base.Node.get_subclass("program"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "programs": {
                    "edge_out": "_ProjectMemberOfProgram_out",
                    "dst_type": base.Node.get_subclass("program"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str , enum=['Open', 'Restricted'])
    def availability_type(self, value):
        self._set_property("availability_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def awg_review(self, value):
        self._set_property("awg_review", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def code(self, value):
        self._set_property("code", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def dbgap_accession_number(self, value):
        self._set_property("dbgap_accession_number", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def disease_type(self, value):
        self._set_property("disease_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def intended_release_date(self, value):
        self._set_property("intended_release_date", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def in_review(self, value):
        self._set_property("in_review", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def is_legacy(self, value):
        self._set_property("is_legacy", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def name(self, value):
        self._set_property("name", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def primary_site(self, value):
        self._set_property("primary_site", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['closed', 'legacy', 'open', 'processed', 'processing', 'review', 'submitted'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def release_requested(self, value):
        self._set_property("release_requested", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def released(self, value):
        self._set_property("released", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def releasable(self, value):
        self._set_property("releasable", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def request_submission(self, value):
        self._set_property("request_submission", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(bool )
    def submission_enabled(self, value):
        self._set_property("submission_enabled", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(Project)
datetime_hooks.cls_inject_updated_datetime_hook(Project)

