"""This module is for ReadGroupQc Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class ReadGroupQc(base.Node):
    __tablename__: str = "node_readgroupqc"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Read Group QC', 'namespace': 'https://gdc.cancer.gov', 'category': 'notation', 'submittable': True, 'downloadable': True, 'description': 'GDC QC run metadata.', 'required': ['submitter_id', 'type'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "read_group_qc"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "read_groups": {
                    "backref": "read_group_qcs",
                    "type": base.Node.get_subclass("read_group"),
                },
                "submitted_aligned_reads_files": {
                    "backref": "read_group_qcs",
                    "type": base.Node.get_subclass("submitted_aligned_reads"),
                },
                "submitted_unaligned_reads_files": {
                    "backref": "read_group_qcs",
                    "type": base.Node.get_subclass("submitted_unaligned_reads"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "read_groups": {
                    "edge_out": "_ReadGroupQcGeneratedFromReadGroup_out",
                    "dst_type": base.Node.get_subclass("read_group"),
                },
                "submitted_aligned_reads_files": {
                    "edge_out": "_ReadGroupQcDataFromSubmittedAlignedReads_out",
                    "dst_type": base.Node.get_subclass("submitted_aligned_reads"),
                },
                "submitted_unaligned_reads_files": {
                    "edge_out": "_ReadGroupQcDataFromSubmittedUnalignedReads_out",
                    "dst_type": base.Node.get_subclass("submitted_unaligned_reads"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def workflow_link(self, value):
        self._set_property("workflow_link", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def workflow_version(self, value):
        self._set_property("workflow_version", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def workflow_start_datetime(self, value):
        self._set_property("workflow_start_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def workflow_end_datetime(self, value):
        self._set_property("workflow_end_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def adapter_content(self, value):
        self._set_property("adapter_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def basic_statistics(self, value):
        self._set_property("basic_statistics", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def encoding(self, value):
        self._set_property("encoding", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def fastq_name(self, value):
        self._set_property("fastq_name", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def kmer_content(self, value):
        self._set_property("kmer_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def overrepresented_sequences(self, value):
        self._set_property("overrepresented_sequences", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_base_sequence_quality(self, value):
        self._set_property("per_base_sequence_quality", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_tile_sequence_quality(self, value):
        self._set_property("per_tile_sequence_quality", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_sequence_quality_score(self, value):
        self._set_property("per_sequence_quality_score", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_base_sequence_content(self, value):
        self._set_property("per_base_sequence_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_sequence_gc_content(self, value):
        self._set_property("per_sequence_gc_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def per_base_n_content(self, value):
        self._set_property("per_base_n_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def percent_gc_content(self, value):
        self._set_property("percent_gc_content", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def sequence_length_distribution(self, value):
        self._set_property("sequence_length_distribution", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['FAIL', 'Not Reported', 'PASS', 'Unknown', 'WARN'])
    def sequence_duplication_levels(self, value):
        self._set_property("sequence_duplication_levels", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def total_sequences(self, value):
        self._set_property("total_sequences", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Read Group Quality Control'])
    def workflow_type(self, value):
        self._set_property("workflow_type", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(ReadGroupQc)
datetime_hooks.cls_inject_updated_datetime_hook(ReadGroupQc)

