"""This module is for SomaticAnnotationWorkflowPerformedOnSimpleSomaticMutation Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class SomaticAnnotationWorkflowPerformedOnSimpleSomaticMutation(base.Edge):
    __tablename__: str = "edge_ba6976cf_soanwopeonsisomu"

    __label__: str = "performed_on"
    __dst_class__: str = "SimpleSomaticMutation"
    __dst_table__: str = "node_simplesomaticmutation"
    __src_class__: str = "SomaticAnnotationWorkflow"
    __src_table__: str = "node_somaticannotationworkflow"

    __dst_src_assoc__: str = "somatic_annotation_workflows"
    __src_dst_assoc__: str = "simple_somatic_mutations"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass