"""This module is for SomaticCopyNumberWorkflowPerformedOnAlignedReads Edge.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class SomaticCopyNumberWorkflowPerformedOnAlignedReads(base.Edge):
    __tablename__: str = "edge_2a6e66ed_soconuwopeonalre"

    __label__: str = "performed_on"
    __dst_class__: str = "AlignedReads"
    __dst_table__: str = "node_alignedreads"
    __src_class__: str = "SomaticCopyNumberWorkflow"
    __src_table__: str = "node_somaticcopynumberworkflow"

    __dst_src_assoc__: str = "somatic_copy_number_workflows"
    __src_dst_assoc__: str = "aligned_reads_files"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass