"""This module is for SubmittedExpressionArray Node.

This module is generated by plaster 0.1.dev140+mmrf from gdcdictionary version master,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class SubmittedExpressionArray(base.Node):
    __tablename__: str = "node_submittedexpressionarray"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [['project_id', 'submitter_id']]

    # _defaults: default value for specified fields in the dictionary
    _defaults:  Dict[str, Union[bool, float, int, str]] = {'state': 'validated', 'file_state': 'registered'}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {'title': 'Submitted Expression Array', 'namespace': 'https://gdc.cancer.gov', 'category': 'data_file', 'submittable': True, 'downloadable': True, 'description': 'Data file containing raw data from an expression array.', 'required': ['submitter_id', 'type', 'file_name', 'file_size', 'md5sum', 'data_category', 'data_format', 'data_type'], 'project': '*', 'program': '*', 'previous_version_downloadable': True}

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "submitted_expression_array"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
                "rna_expression_workflows": {
                    "name": "submitted_expression_arrays",
                    "src_type": base.Node.get_subclass("rna_expression_workflow"),
                },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
                "aliquots": {
                    "backref": "submitted_expression_arrays",
                    "type": base.Node.get_subclass("aliquot"),
                },
                "core_metadata_collections": {
                    "backref": "submitted_expression_arrays",
                    "type": base.Node.get_subclass("core_metadata_collection"),
                },
                "rna_expression_workflows": {
                    "backref": "submitted_expression_arrays",
                    "type": base.Node.get_subclass("rna_expression_workflow"),
                },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
                "aliquots": {
                    "edge_out": "_SubmittedExpressionArrayDerivedFromAliquot_out",
                    "dst_type": base.Node.get_subclass("aliquot"),
                },
                "core_metadata_collections": {
                    "edge_out": "_SubmittedExpressionArrayDataFromCoreMetadataCollection_out",
                    "dst_type": base.Node.get_subclass("core_metadata_collection"),
                },
        }


    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False


    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )


    @psqlgraph.pg_property(str )
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['error', 'invalid', 'live', 'md5summed', 'md5summing', 'redacted', 'released', 'submitted', 'suppressed', 'uploaded', 'uploading', 'validated', 'validating'])
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str, type(None) )
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def file_name(self, value):
        self._set_property("file_name", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(int )
    def file_size(self, value):
        self._set_property("file_size", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def md5sum(self, value):
        self._set_property("md5sum", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['deleted', 'error', 'processed', 'processing', 'registered', 'released', 'submitted', 'uploaded', 'uploading', 'validated', 'validating'])
    def file_state(self, value):
        self._set_property("file_state", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['file_format', 'file_size', 'md5sum'])
    def error_type(self, value):
        self._set_property("error_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def state_comment(self, value):
        self._set_property("state_comment", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str )
    def object_id(self, value):
        self._set_property("object_id", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Transcriptome Profiling'])
    def data_category(self, value):
        self._set_property("data_category", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['CEL'])
    def data_format(self, value):
        self._set_property("data_format", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Raw Intensities'])
    def data_type(self, value):
        self._set_property("data_type", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['Expression Array'])
    def experimental_strategy(self, value):
        self._set_property("experimental_strategy", value)  # type: ignore  # inherited from CommonBase


    @psqlgraph.pg_property(str , enum=['GeneChip U133 Plus 2.0', 'GeneChip U133A'])
    def platform(self, value):
        self._set_property("platform", value)  # type: ignore  # inherited from CommonBase



datetime_hooks.cls_inject_created_datetime_hook(SubmittedExpressionArray)
datetime_hooks.cls_inject_updated_datetime_hook(SubmittedExpressionArray)

